apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plugins.configuration.inendless.io
spec:
  group: configuration.inendless.io
  names:
    kind: Plugin
    listKind: PluginList
    plural: plugins
    singular: plugin
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              limits:
                properties:
                  maxRequestBodySize:
                    type: integer
                type: object
              removePrefix:
                properties:
                  prefixes:
                    items:
                      type: string
                    type: array
                type: object
              addPrefix:
                properties:
                  prefix:
                    type: string
                type: object
              jwtBearer:
                properties:
                  audience:
                    type: string
                  secret:
                    type: string
                  issuer:
                    type: string
                  openIdConfiguration:
                    type: string 
                type: object
              rateLimiter:
                properties:
                  permitLimit:
                    type: number
                  window:
                    type: number
                  queueLimit:
                    type: number
                type: object
              protocol:
                properties:
                  policy:
                    type: string
                type: object    
              cors:
                properties:
                  allowOrigins:
                    items:
                      type: string
                    type: array
                  allowMethods:
                    items:
                      type: string
                    type: array
                  allowHeaders:
                    items:
                      type: string
                    type: array
                type: object